import { createClient } from '@supabase/supabase-js';

// Initialize Supabase - Using Service Role Key or Anon Key
// Service Role is preferred for backend operations to bypass RLS if configured
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
const supabase = createClient(supabaseUrl, supabaseKey);

export interface Property {
    id: string;
    title: string;
    type: string;
    price: string;
    image?: string;
    images?: string[];
    location: string;
    neighborhood?: string;
    code?: string;
    bedrooms: number;
    bathrooms?: number;
    suites?: number;
    garage?: number;
    area: string; // Deprecated/Fallback
    landArea?: string; // Mapped to land_area
    builtArea?: string; // Mapped to built_area
    description: string;
    features?: string[];
}

export async function getProperties(): Promise<Property[]> {
    try {
        const { data, error } = await supabase
            .from('properties')
            .select('*')
            .order('created_at', { ascending: false });

        if (error) {
            console.error('Error fetching properties from Supabase:', error);
            return [];
        }

        // Map DB snake_case to TS camelCase
        return (data || []).map((p: any) => ({
            ...p,
            landArea: p.land_area,
            builtArea: p.built_area,
            // ensure id is string
            id: String(p.id)
        }));
    } catch (error) {
        console.error('Unexpected error fetching properties:', error);
        return [];
    }
}

export async function saveProperty(property: Property): Promise<Property | null> {
    try {
        // Map TS camelCase to DB snake_case
        // Omit id if it's "Date.now()" style generated by frontend, let DB generate UUID?
        // Actually the current frontend generates ID. Let's keep using it 
        // to avoid breaking changes, OR switch to DB generated UUID.
        // It's safer to let Supabase generate UUIDs if id is empty or invalid.
        // But the Property interface has id.
        // If frontend sends an ID (like Date.now()), we can use it if the column type allows,
        // but UUID column expects UUID.
        // The SQL defined ID as UUID DEFAULT gen_random_uuid().
        // If frontend sends "170...", that's not UUID. It will fail.
        // So we should OMIT the ID if it's not a valid UUID, or change SQL to TEXT.
        // I changed SQL to UUID DEFAULT gen_random_uuid() for best practice, but frontend sends timestamp.
        // To be safe and compatible with existing frontend logic, I should probably allow the ID column to be TEXT or change frontend logic.
        // The SQL I wrote uses UUID.
        // Frontend uses Date.now().toString().
        // I will update the SQL in the file I wrote? No, I already wrote it.
        // I should update SQL to TEXT for ID to be safe with existing frontend ID generation logic, 
        // OR update frontend to not send ID and let backend handle it.
        // Frontend `app/api/properties/route.ts` generates ID: `id: Date.now().toString()`.

        // Let's modify saveProperty to IGNORE the input ID if it looks like a timestamp and let DB generate one? 
        // No, then frontend won't know the ID of the new item without re-fetching.
        // The best approach is to let DB generate ID and return it.

        const { id, ...rest } = property;

        const dbProperty = {
            title: rest.title,
            type: rest.type,
            price: rest.price,
            image: rest.image,
            images: rest.images,
            location: rest.location,
            neighborhood: rest.neighborhood,
            code: rest.code,
            bedrooms: rest.bedrooms,
            bathrooms: rest.bathrooms || 0,
            suites: rest.suites,
            garage: rest.garage || 0,
            area: rest.area,
            land_area: rest.landArea,
            built_area: rest.builtArea,
            description: rest.description,
            features: rest.features || []
            // We let DB generate ID
        };

        const { data, error } = await supabase
            .from('properties')
            .insert([dbProperty])
            .select()
            .single();

        if (error) {
            console.error('Error saving property to Supabase:', error);
            throw error;
        }

        if (data) {
            return {
                ...data,
                landArea: data.land_area,
                builtArea: data.built_area,
                id: String(data.id)
            };
        }
        return null;
    } catch (error) {
        console.error('Unexpected error saving property:', error);
        throw error;
    }
}

export async function updateProperty(id: string, property: Partial<Property>): Promise<Property | null> {
    try {
        const { id: _, ...rest } = property;

        const dbProperty: Record<string, unknown> = {};
        if (rest.title !== undefined) dbProperty.title = rest.title;
        if (rest.type !== undefined) dbProperty.type = rest.type;
        if (rest.price !== undefined) dbProperty.price = rest.price;
        if (rest.image !== undefined) dbProperty.image = rest.image;
        if (rest.images !== undefined) dbProperty.images = rest.images;
        if (rest.location !== undefined) dbProperty.location = rest.location;
        if (rest.neighborhood !== undefined) dbProperty.neighborhood = rest.neighborhood;
        if (rest.code !== undefined) dbProperty.code = rest.code;
        if (rest.bedrooms !== undefined) dbProperty.bedrooms = rest.bedrooms;
        if (rest.bathrooms !== undefined) dbProperty.bathrooms = rest.bathrooms || 0;
        if (rest.suites !== undefined) dbProperty.suites = rest.suites;
        if (rest.garage !== undefined) dbProperty.garage = rest.garage || 0;
        if (rest.area !== undefined) dbProperty.area = rest.area;
        if (rest.landArea !== undefined) dbProperty.land_area = rest.landArea;
        if (rest.builtArea !== undefined) dbProperty.built_area = rest.builtArea;
        if (rest.description !== undefined) dbProperty.description = rest.description;
        if (rest.features !== undefined) dbProperty.features = rest.features || [];

        const { data, error } = await supabase
            .from('properties')
            .update(dbProperty)
            .eq('id', id)
            .select()
            .single();

        if (error) {
            console.error('Error updating property in Supabase:', error);
            throw error;
        }

        if (data) {
            return {
                ...data,
                landArea: data.land_area,
                builtArea: data.built_area,
                id: String(data.id)
            };
        }
        return null;
    } catch (error) {
        console.error('Unexpected error updating property:', error);
        throw error;
    }
}

export async function deleteProperty(id: string): Promise<boolean> {
    try {
        const { error } = await supabase
            .from('properties')
            .delete()
            .eq('id', id);

        if (error) {
            console.error('Error deleting property from Supabase:', error);
            return false;
        }
        return true;
    } catch (error) {
        console.error('Unexpected error deleting property:', error);
        return false;
    }
}

export async function getPropertyById(id: string): Promise<Property | null> {
    try {
        const { data, error } = await supabase
            .from('properties')
            .select('*')
            .eq('id', id)
            .single();

        if (error) {
            console.error('Error fetching property by ID:', error);
            return null;
        }

        if (data) {
            return {
                ...data,
                landArea: data.land_area,
                builtArea: data.built_area,
                id: String(data.id)
            };
        }
        return null;
    } catch (error) {
        console.error('Unexpected error fetching property by ID:', error);
        return null;
    }
}

export async function getSimilarProperties(type: string, location: string, currentId: string): Promise<Property[]> {
    try {
        const { data, error } = await supabase
            .from('properties')
            .select('*')
            .neq('id', currentId)
            .or(`type.eq.${type},location.eq.${location}`)
            .limit(4);

        if (error) {
            console.error('Error fetching similar properties:', error);
            return [];
        }

        return (data || []).map((p: any) => ({
            ...p,
            landArea: p.land_area,
            builtArea: p.built_area,
            id: String(p.id)
        }));
    } catch (error) {
        console.error('Unexpected error fetching similar properties:', error);
        return [];
    }
}

export interface SearchFilters {
    type?: string;
    neighborhood?: string;
    bedrooms?: number;
    minPrice?: number;
    maxPrice?: number;
    query?: string;
}

export async function searchProperties(filters: SearchFilters): Promise<Partial<Property>[]> {
    try {
        let query = supabase
            .from('properties')
            .select('id, title, type, neighborhood, price, bedrooms, bathrooms, area, land_area, built_area, garage, images, location, description')
            .order('created_at', { ascending: false });

        if (filters.type) {
            query = query.ilike('type', `%${filters.type}%`);
        }

        if (filters.neighborhood) {
            query = query.ilike('neighborhood', `%${filters.neighborhood}%`);
        }

        if (filters.bedrooms) {
            query = query.gte('bedrooms', filters.bedrooms);
        }

        if (filters.minPrice) {
            query = query.gte('price', filters.minPrice);
        }

        if (filters.maxPrice) {
            query = query.lte('price', filters.maxPrice);
        }

        const { data, error } = await query;

        if (error) {
            console.error('Error searching properties:', error);
            return [];
        }

        let results = (data || []).map((p: any) => ({
            id: String(p.id),
            title: p.title,
            type: p.type,
            neighborhood: p.neighborhood,
            price: p.price,
            bedrooms: p.bedrooms,
            bathrooms: p.bathrooms,
            area: p.area,
            landArea: p.land_area,
            builtArea: p.built_area,
            garage: p.garage,
            images: p.images || [],
            location: p.location,
            description: p.description,
        }));

        // Client-side free-text filter on title, description, location
        if (filters.query) {
            const q = filters.query.toLowerCase();
            results = results.filter(p =>
                (p.title && p.title.toLowerCase().includes(q)) ||
                (p.description && p.description.toLowerCase().includes(q)) ||
                (p.location && p.location.toLowerCase().includes(q)) ||
                (p.neighborhood && p.neighborhood.toLowerCase().includes(q))
            );
        }

        return results;
    } catch (error) {
        console.error('Unexpected error searching properties:', error);
        return [];
    }
}
